apps/core/urls.py
from django.urls import path

import apps.core.views as views

app_name = 'core'

urlpatterns = [
    path(r'', views.RootView.as_view(), name='root'),
]

apps/leads/urls.py
from django.urls import path
from apps.leads import views as LeadViews

app_name = 'leads'

urlpatterns = [
    path(r'list/', LeadViews.LeadsListView, name='list-leads'),
    path(r'add/', LeadViews.LeadsAddView, name='add-lead'),
]

djangodemo/urls.py
from django.conf import settings
from django.conf.urls import include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path(r'', include('apps.core.urls', namespace='core')),
    path(r'', include('apps.leads.urls', namespace='lolz')),
    path(settings.ADMIN_URL, admin.site.urls),
]

apps/core/models.py
from django.db import models

# Create your models here.

apps/leads/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _


class Lead(models.Model):
    class Meta:
        verbose_name = _("Lead")
        verbose_name_plural = _("Leads")

    name = models.CharField(max_length=255, null=False, blank=False)
    email = models.EmailField(unique=True, null=False, blank=False)

    def __str__(self):
        return self.name

apps/leads/forms.py
from django import forms

from apps.leads.models import Lead


class LeadForm(forms.ModelForm):

    class Meta:
        model = Lead
        fields = ('name', 'email', )

apps/core/views.py
from django.views.generic import TemplateView


class RootView(TemplateView):

    template_name = 'index.html'

apps/leads/views.py
from django.shortcuts import render
from django.views.decorators.http import require_http_methods
from apps.leads.models import Lead
from apps.leads.forms import LeadForm


@require_http_methods(['GET'])
def LeadsListView(request):
    leads = Lead.objects.all()
    return render(request, 'leads/list.html', {'leads': leads})


@require_http_methods(['GET', 'POST'])
def LeadsAddView(request):
    if request.method == "POST":
        action = request.POST.get('action')
        form = LeadForm(request.POST)
        if form.is_valid():
            form.save()
            if action == "redirect":
                return render(
                    request, 'leads/list.html', {'leads': Lead.objects.all()})
            else:
                form = LeadForm()
    else:
        form = LeadForm()
    return render(request, 'leads/add.html', {'form': form})

templates/base.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <title>Demo Django App</title>
  <meta name="description" content="This is out new cool product. a demo app dude.">
  <meta name="viewport" content="width=device-width" />

   <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap.min.css">
  <script
  src="https://code.jquery.com/jquery-1.9.1.min.js"
  integrity="sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+rPA0VL2rbQ="
  crossorigin="anonymous"></script>
  <script src="{% static 'bootstrap.min.js' %}"></script>
{% block data_head %}
{% endblock %}
</head>

<body class="fancy-bg" style="padding-top: 70px;">

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'core:root'%}">DemoApp</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right" padding-right="50px">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Views <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <br>
            <li><a href="{% url 'leads:add-lead'%}">Add </a></li>
            <li><a href="{% url 'leads:list-leads'%}">List </a></li>
            <li role="separator" class="divider"></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load i18n %}
  {% block body %}
  <div class="container-fluid">
    <h1 style="padding-left: 20px"> Welcome! </h1>
    <h3 style="padding-left: 20px"> This a demo welcome page, for a demo django app, because we are in a demo world </h3>
    <h5 style="padding-left: 20px;"> You get where I am going with this, right? </h5>
    <div class="list-group col-md-6" style="padding: 50px; padding-top: 10px; font-size: 150%" align="center">
      <a href="{% url 'leads:add-lead'%}" class="list-group-item list-group-item-action">Add </a>
      <a href="{% url 'leads:list-leads'%}" class="list-group-item list-group-item-action">List </a>
    </div>
  </div>
  {% endblock %}

templates/leads/add.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block body %}
<div class="container">
    <br>
    <div class="col-xs-4"></div>
    <div class="col-xs-4">
    <form method="POST" class="post-form" style="align-self: center;">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default" name="action" value="redirect">Save</button>
        <button type="submit" class="save btn btn-default" name="action" value="reload">Save and add another</button>
    </form></div>
</div>

{% endblock %}

templates/leads/list.html
{% extends 'base.html' %}
{% load staticfiles %}

{%block data_head%}
  <script
  src="https://code.jquery.com/jquery-1.9.1.min.js"
  integrity="sha256-wS9gmOZBqsqWxgIVgA8Y9WcQOa7PgSIX+rPA0VL2rbQ="
  crossorigin="anonymous"></script>
  <script src="{% static 'cohort/bootstrap.min.js' %}"></script>
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.7.1/js/bootstrap-datepicker.min.js"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/3.1.2/js/dataTables.bootstrap.min.js"></script>
   <script src="https://cdn.datatables.net/fixedheader/3.1.2/js/dataTables.fixedHeader.min.js" type="text/javascript"></script>
   <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/fixedheader/3.1.2/css/fixedHeader.dataTables.min.css">
   <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.8.4/moment.min.js"></script>
   <script type="text/javascript" src="https://cdn.datatables.net/plug-ins/1.10.16/sorting/datetime-moment.js"></script>
   <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/numeral.js/2.0.6/numeral.min.js"></script>
  <script src="{% static 'order-engagement.js' %}"></script>
  <style>
  table.fixedHeader-floating {
    padding-top: 45px;
  }
  </style>
  <script type="text/javascript" class="init">

    $(document).ready(function() {
      $.fn.dataTable.moment( 'DD, MMM. YYYY, HH:mm' );
      $('#example').DataTable({
        "fixedHeader": {
        header: true,
        },
        "paging": false,
      }); });
    </script>
{%endblock%}

{% block body %}
<div class="container">
  <div class="row">
    <div class="table-responsive" style="text-align: center">
      <br>
      <h3> Leads List </h3>
      <br>
      <table id="example" class="table table-striped table-bordered">
        <thead>
          <tr>
            <th style="text-align: center">ID</th>
            <th style="text-align: center">Name</th>
            <th style="text-align: center">Email</th>
          </tr>
        </thead>
        <tbody>
          {% for lead in leads %}
          <tr>
            <td>{{lead.id}}</td>
            <td>{{lead.name}}</td>
            <td>{{lead.email}}</td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
</div>

{% endblock %}